import {
  Component,
  EventEmitter,
  Input,
  Output,
  computed,
  inject,
  signal,
} from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { FormField, OptionSource } from '../models/form-field.model';
import { normalizeFieldOption, normalizeStaticSelectFieldOptions } from '../utils/field-options.utils';
import { buildPlaceholderFromLabel, supportsPlaceholderAutoGeneration } from '../utils/form-field.factory';
import {
  getLocationFieldDeleteBlockReason,
  resolveBuilderLocationKind,
  schemaHasLocationKind,
} from '../utils/location-field-dependencies.utils';
import { isUniqueDynamicModuleOptionDisabled } from '../utils/unique-dynamic-modules.utils';
import { DynamicModuleOptionsService } from '../services/dynamic-module-options.service';
import { FormModuleListItem } from '../../forms/models/form-module.model';

type SelectOptionsMode = 'static' | 'dynamic';

interface ModuleDataCache {
  records: Record<string, unknown>[];
  columns: string[];
}

interface LoadModuleDataOptions {
  preserveDisplayColumn?: boolean;
  emitUpdate?: boolean;
}

@Component({
  selector: 'app-field-settings',
  standalone: false,
  templateUrl: './field-settings.component.html',
  styleUrl: './field-settings.component.scss',
})
export class FieldSettingsComponent {
  private readonly toastr = inject(ToastrService);
  private readonly schemaSignal = signal<FormField[]>([]);
  private readonly selectedFieldIdSignal = signal<string | null>(null);

  @Input() activeModuleName = '';

  /**
   * When true (Edit Form Builder on user/item/vendor setup), each Dynamic Module
   * may only be assigned to one Select field in the current form.
   */
  @Input() enforceUniqueDynamicModules = false;

  @Input() set schema(value: FormField[] | null | undefined) {
    this.schemaSignal.set(value ?? []);
  }

  /** Country on another field — required before States/Cities can be selected. */
  readonly hasCountryField = computed(() =>
    schemaHasLocationKind(
      this.schemaSignal(),
      'countries',
      this.selectedFieldIdSignal() ?? undefined
    )
  );

  @Input() set field(value: FormField | undefined) {
    if (!value) {
      return;
    }

    this.selectedFieldIdSignal.set(value.id);

    const isSameField = this._field?.id === value.id;

    if (this.skipFieldReinitialize && isSameField) {
      this.skipFieldReinitialize = false;
      this.assignField(value);
      return;
    }

    const preservedModuleSlug = isSameField ? this.selectedModuleSlug : '';
    const preservedDisplayColumn = isSameField ? this.selectedDisplayColumn : '';

    this.assignField(value);
    this.initializeSelectOptionsState(
      this._field,
      preservedModuleSlug,
      preservedDisplayColumn
    );
  }

  get field(): FormField | undefined {
    return this._field;
  }

  private _field!: FormField;
  private placeholderManuallyEdited = false;
  private skipFieldReinitialize = false;
  private modulesLoaded = false;
  private modulesLoadPending = false;
  private modulesLoadCallbacks: Array<() => void> = [];
  private loadingModuleSlug: string | null = null;
  private apiLoadingCount = 0;
  private readonly moduleDataBySlug = new Map<string, ModuleDataCache>();

  optionsMode: SelectOptionsMode = 'static';
  availableModules: FormModuleListItem[] = [];
  selectedModuleSlug = '';
  selectedDisplayColumn = '';
  moduleRecords: Record<string, unknown>[] = [];
  moduleColumns: string[] = [];

  modulesLoading = false;
  modulesError: string | null = null;
  recordsLoading = false;

  @Output() update = new EventEmitter<FormField>();
  @Output() duplicate = new EventEmitter<void>();
  @Output() delete = new EventEmitter<void>();
  @Output() loadingChange = new EventEmitter<boolean>();

  constructor(private dynamicModuleOptionsService: DynamicModuleOptionsService) {}

  onChange(): void {
    if (!this._field || !this.isFieldEditable) {
      return;
    }

    this.update.emit({
      ...this._field,
      isShow: this._field.isShow !== false,
      isReadonly: this._field.isReadonly === true,
      options: [...(this._field.options || [])],
      optionSource: this.resolveEmittedOptionSource(),
      selectionType:
        this._field.type === 'select'
          ? this._field.selectionType === 'multi'
            ? 'multi'
            : 'single'
          : undefined,
      condition: this._field.condition
        ? { ...this._field.condition }
        : { fieldId: '', value: '' },
    });
  }

  onLabelChange(): void {
    if (!this._field || !this.isFieldEditable) {
      return;
    }

    if (
      !this.placeholderManuallyEdited &&
      supportsPlaceholderAutoGeneration(this._field.type)
    ) {
      this._field.placeholder = buildPlaceholderFromLabel(this._field.label);
    }

    this.onChange();
  }

  onPlaceholderChange(): void {
    if (!this._field || !this.isFieldEditable) {
      return;
    }

    this.placeholderManuallyEdited = !this.isAutoGeneratedPlaceholder(this._field);
    this.onChange();
  }

  private isAutoGeneratedPlaceholder(field: FormField): boolean {
    if (!supportsPlaceholderAutoGeneration(field.type)) {
      return false;
    }

    const placeholder = (field.placeholder ?? '').trim();
    return !placeholder || placeholder === buildPlaceholderFromLabel(field.label);
  }

  onShowChange(show: boolean): void {
    if (!this._field || !this.isFieldEditable) {
      return;
    }

    this._field.isShow = show;
    this.onChange();
  }

  get isFieldHidden(): boolean {
    return this._field?.isShow === false;
  }

  get isFieldEditable(): boolean {
    return this._field?.isEditable !== false;
  }

  get isSelectField(): boolean {
    return this._field?.type === 'select';
  }

  /** Selection Type (Single/Multi) — only for user/item/vendor setup Form Builders. */
  get supportsSelectSelectionType(): boolean {
    if (!this.isSelectField) {
      return false;
    }

    const moduleName = (this.activeModuleName || '').trim().toLowerCase();
    return moduleName === 'users' || moduleName === 'items' || moduleName === 'vendors';
  }

  get selectionType(): 'single' | 'multi' {
    return this._field?.selectionType === 'multi' ? 'multi' : 'single';
  }

  setSelectionType(type: 'single' | 'multi'): void {
    if (!this._field || !this.isFieldEditable || !this.supportsSelectSelectionType) {
      return;
    }

    this._field.selectionType = type;
    this.onChange();
  }

  get isParameterField(): boolean {
    return this._field?.type === 'parameter';
  }

  get isRatingField(): boolean {
    return this._field?.type === 'rating';
  }

  get isRangeField(): boolean {
    return this._field?.type === 'range';
  }

  readonly parameterCategories = [
    { label: 'Currency', value: 'currency' },
    { label: 'Length / Distance', value: 'length' },
    { label: 'Weight / Mass', value: 'weight' },
    { label: 'Volume / Capacity', value: 'volume' },
  ];

  get parameterUnits(): { label: string; value: string }[] {
    switch (this._field?.parameterCategory) {
      case 'currency':
        return [
          { label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' },
          { label: 'GBP', value: 'GBP' }, { label: 'PKR', value: 'PKR' },
          { label: 'INR', value: 'INR' }, { label: 'JPY', value: 'JPY' },
          { label: 'CNY', value: 'CNY' }, { label: 'CAD', value: 'CAD' },
          { label: 'AUD', value: 'AUD' },
        ];
      case 'length':
        return [
          { label: 'Meter (m)', value: 'm' }, { label: 'Centimeter (cm)', value: 'cm' },
          { label: 'Millimeter (mm)', value: 'mm' }, { label: 'Kilometer (km)', value: 'km' },
          { label: 'Inch (in)', value: 'in' }, { label: 'Foot (ft)', value: 'ft' },
          { label: 'Yard (yd)', value: 'yd' }, { label: 'Mile (mi)', value: 'mi' },
        ];
      case 'weight':
        return [
          { label: 'Kilogram (kg)', value: 'kg' }, { label: 'Gram (g)', value: 'g' },
          { label: 'Milligram (mg)', value: 'mg' }, { label: 'Pound (lb)', value: 'lb' },
          { label: 'Ounce (oz)', value: 'oz' }, { label: 'Ton', value: 'ton' },
        ];
      case 'volume':
        return [
          { label: 'Liter (L)', value: 'L' }, { label: 'Milliliter (mL)', value: 'mL' },
          { label: 'Gallon (gal)', value: 'gal' }, { label: 'Quart (qt)', value: 'qt' },
          { label: 'Pint (pt)', value: 'pt' }, { label: 'Cup', value: 'cup' },
          { label: 'Cubic Meter (m³)', value: 'm3' },
        ];
      default:
        return [];
    }
  }

  get dynamicOptionsCount(): number {
    return this.optionsMode === 'dynamic' ? this._field?.options?.length ?? 0 : 0;
  }

  setOptionsMode(mode: SelectOptionsMode): void {
    if (!this.isFieldEditable) {
      return;
    }

    this.optionsMode = mode;

    if (mode === 'dynamic') {
      this.selectedModuleSlug = '';
      this.selectedDisplayColumn = '';
      this.moduleRecords = [];
      this.moduleColumns = [];
      this._field.optionSource = undefined;
      this.ensureModulesLoaded();
      return;
    }

    this.onChange();
  }

  onModuleChange(moduleSlug: string): void {
    if (!this.isFieldEditable) {
      return;
    }

    if (!moduleSlug) {
      this.selectedModuleSlug = '';
      this.selectedDisplayColumn = '';
      this.moduleRecords = [];
      this.moduleColumns = [];
      this._field.options = [];
      this._field.optionSource = undefined;
      this.onChange();
      return;
    }

    if (this.isModuleSlugDisabled(moduleSlug)) {
      return;
    }

    this.selectedModuleSlug = moduleSlug;
    this.selectedDisplayColumn = '';
    this.moduleRecords = [];
    this.moduleColumns = [];

    this.loadModuleData(moduleSlug, {
      preserveDisplayColumn: false,
      emitUpdate: true,
    });
  }

  isModuleOptionDisabled(module: FormModuleListItem): boolean {
    return this.isModuleSlugDisabled(this.getModuleSlug(module));
  }

  private isModuleSlugDisabled(moduleSlug: string): boolean {
    if (
      this.enforceUniqueDynamicModules &&
      isUniqueDynamicModuleOptionDisabled(
        moduleSlug,
        this.schemaSignal(),
        this.selectedFieldIdSignal() ?? undefined
      )
    ) {
      return true;
    }

    const kind = resolveBuilderLocationKind(moduleSlug);

    if (kind !== 'states' && kind !== 'cities') {
      return false;
    }

    return !this.hasCountryField();
  }

  onDisplayColumnChange(column: string): void {
    if (!this.isFieldEditable) {
      return;
    }

    this.selectedDisplayColumn = column;

    if (!column) {
      this._field.options = [];
      this._field.optionSource = undefined;
      this.onChange();
      return;
    }

    this.commitDynamicOptions();
  }

  onParameterCategoryChange(category: string): void {
    if (!this.isFieldEditable || !this._field) return;
    this._field.parameterCategory = category;
    this._field.parameterUnit = '';
    this.onChange();
  }

  onParameterUnitChange(unit: string): void {
    if (!this.isFieldEditable || !this._field) return;
    this._field.parameterUnit = unit;
    this.onChange();
  }

  onMaxRatingChange(value: number): void {
    if (!this.isFieldEditable || !this._field) return;
    this._field.maxRating = value;
    this.onChange();
  }

  getModuleSlug(form: FormModuleListItem): string {
    return this.dynamicModuleOptionsService.getModuleSlug(form);
  }

  getModuleLabel(form: FormModuleListItem): string {
    return this.dynamicModuleOptionsService.getModuleLabel(form);
  }

  getModuleLabelBySlug(moduleSlug: string): string {
    const module = this.availableModules.find(
      item => this.getModuleSlug(item) === moduleSlug
    );

    return module ? this.getModuleLabel(module) : moduleSlug;
  }

  updateOptions(event: Event): void {
    if (!this._field || !this.isFieldEditable) {
      return;
    }

    const value = (event.target as HTMLTextAreaElement).value;
    const labels = value
      .split('\n')
      .map(v => v.trim())
      .filter(v => v);

    if (this.isSelectField && this.optionsMode === 'static') {
      this._field.options = normalizeStaticSelectFieldOptions(labels);
    } else {
      this._field.options = labels;
    }

    this._field.optionSource = undefined;
    this.onChange();
  }

  get optionsText(): string {
    return (this._field?.options || [])
      .map(option => {
        if (typeof option === 'string') {
          return option;
        }

        return normalizeFieldOption(option)?.label ?? '';
      })
      .filter(Boolean)
      .join('\n');
  }

  onDuplicateClick(): void {
    if (!this.isFieldEditable) {
      return;
    }

    this.duplicate.emit();
  }

  isDeleteModalOpen = false;

  onDeleteClick(): void {
    if (!this.isFieldEditable) {
      return;
    }

    const blockReason = getLocationFieldDeleteBlockReason(
      this._field,
      this.schemaSignal()
    );

    if (blockReason) {
      this.toastr.warning(blockReason);
      return;
    }

    this.isDeleteModalOpen = true;
  }

  onDeleteConfirm(): void {
    const blockReason = getLocationFieldDeleteBlockReason(
      this._field,
      this.schemaSignal()
    );

    if (blockReason) {
      this.isDeleteModalOpen = false;
      this.toastr.warning(blockReason);
      return;
    }

    this.isDeleteModalOpen = false;
    this.delete.emit();
  }

  onDeleteModalClose(): void {
    this.isDeleteModalOpen = false;
  }

  private assignField(value: FormField): void {
    this._field = {
      ...value,
      defaultValue: value.defaultValue ?? value.value ?? '',
      width: value.width ?? 12,
      validations: value.validations || {},
      condition: value.condition || { fieldId: '', value: '' },
      options: [...(value.options || [])],
      optionSource: value.optionSource ? { ...value.optionSource } : undefined,
      selectionType:
        value.type === 'select'
          ? value.selectionType === 'multi'
            ? 'multi'
            : 'single'
          : undefined,
      isShow: value.isShow !== false,
      isReadonly: value.isReadonly === true,
    };

    this.placeholderManuallyEdited = !this.isAutoGeneratedPlaceholder(this._field);
  }

  private initializeSelectOptionsState(
    field: FormField,
    preservedModuleSlug = '',
    preservedDisplayColumn = ''
  ): void {
    const dynamicConfig = this.readDynamicConfig(field);

    this.optionsMode = this.resolveOptionsMode(field);

    if (preservedModuleSlug) {
      this.selectedModuleSlug = preservedModuleSlug;
      this.selectedDisplayColumn =
        preservedDisplayColumn || dynamicConfig?.displayColumn || '';
    } else if (dynamicConfig) {
      this.selectedModuleSlug = dynamicConfig.moduleSlug;
      this.selectedDisplayColumn = dynamicConfig.displayColumn;
    } else {
      this.selectedModuleSlug = '';
      this.selectedDisplayColumn = '';
    }

    this.restoreModuleDataFromCache();

    if (this.optionsMode === 'dynamic') {
      this.ensureModulesLoaded(() => {
        if (this.selectedModuleSlug) {
          this.loadModuleData(this.selectedModuleSlug, {
            preserveDisplayColumn: true,
            emitUpdate: false,
          });
        }
      });
      return;
    }

    if (field.type === 'select') {
      this._field.options = normalizeStaticSelectFieldOptions(this._field.options);
    }
  }

  private restoreModuleDataFromCache(): void {
    if (!this.selectedModuleSlug) {
      this.moduleRecords = [];
      this.moduleColumns = [];
      return;
    }

    const cached = this.moduleDataBySlug.get(this.selectedModuleSlug);

    if (cached) {
      this.moduleRecords = cached.records;
      this.moduleColumns = cached.columns;
      return;
    }

    this.moduleRecords = [];
    this.moduleColumns = [];
  }

  private resolveOptionsMode(field: FormField): SelectOptionsMode {
    return field.optionSource?.type === 'dynamic' ? 'dynamic' : 'static';
  }

  private ensureModulesLoaded(onLoaded?: () => void): void {
    if (this.modulesLoaded) {
      onLoaded?.();
      return;
    }

    if (onLoaded) {
      this.modulesLoadCallbacks.push(onLoaded);
    }

    if (this.modulesLoadPending) {
      return;
    }

    this.modulesLoadPending = true;
    this.modulesLoading = true;
    this.modulesError = null;
    this.beginApiLoading();

    this.dynamicModuleOptionsService
      .getAvailableModules(this.activeModuleName)
      .subscribe({
        next: modules => {
          this.availableModules = modules;
          this.modulesLoaded = true;
          this.modulesLoading = false;
          this.modulesLoadPending = false;
          this.endApiLoading();
          this.flushModulesLoadCallbacks();
        },
        error: () => {
          this.availableModules = [];
          this.modulesLoaded = false;
          this.modulesLoading = false;
          this.modulesLoadPending = false;
          this.modulesError = 'Failed to load form modules.';
          this.endApiLoading();
          this.flushModulesLoadCallbacks();
        },
      });
  }

  private flushModulesLoadCallbacks(): void {
    const callbacks = [...this.modulesLoadCallbacks];
    this.modulesLoadCallbacks = [];
    callbacks.forEach(callback => callback());
  }

  private loadModuleData(
    moduleSlug: string,
    options: LoadModuleDataOptions = {}
  ): void {
    const { preserveDisplayColumn = false, emitUpdate = true } = options;

    const cached = this.moduleDataBySlug.get(moduleSlug);

    if (cached) {
      this.recordsLoading = false;
      this.applyLoadedModuleData(cached, preserveDisplayColumn, emitUpdate);
      return;
    }

    if (this.loadingModuleSlug === moduleSlug) {
      return;
    }

    this.loadingModuleSlug = moduleSlug;
    this.recordsLoading = true;
    this.beginApiLoading();

    this.dynamicModuleOptionsService.getModuleData(moduleSlug).subscribe({
      next: moduleData => {
        this.recordsLoading = false;
        this.loadingModuleSlug = null;
        this.endApiLoading();
        this.moduleDataBySlug.set(moduleSlug, moduleData);
        this.applyLoadedModuleData(moduleData, preserveDisplayColumn, emitUpdate);
      },
      error: () => {
        this.recordsLoading = false;
        this.loadingModuleSlug = null;
        this.endApiLoading();
      },
    });
  }

  private beginApiLoading(): void {
    this.apiLoadingCount += 1;

    if (this.apiLoadingCount === 1) {
      this.loadingChange.emit(true);
    }
  }

  private endApiLoading(): void {
    this.apiLoadingCount = Math.max(0, this.apiLoadingCount - 1);

    if (this.apiLoadingCount === 0) {
      this.loadingChange.emit(false);
    }
  }

  private applyLoadedModuleData(
    data: ModuleDataCache,
    preserveDisplayColumn: boolean,
    emitUpdate: boolean
  ): void {
    this.moduleRecords = data.records;
    this.moduleColumns = data.columns;

    if (
      !preserveDisplayColumn ||
      !this.selectedDisplayColumn ||
      !this.moduleColumns.includes(this.selectedDisplayColumn)
    ) {
      this.selectedDisplayColumn =
        this.dynamicModuleOptionsService.getDefaultDisplayColumn(
          this.moduleColumns
        );
    }

    if (emitUpdate && this.selectedDisplayColumn) {
      this.commitDynamicOptions();
    }
  }

  private commitDynamicOptions(): void {
    if (!this._field || !this.selectedModuleSlug || !this.selectedDisplayColumn) {
      return;
    }

    this._field.options = this.moduleRecords.length
      ? this.dynamicModuleOptionsService.buildOptionsFromRecords(
          this.moduleRecords,
          this.selectedDisplayColumn
        )
      : [];
    this._field.optionSource = this.buildDynamicOptionSource();
    this.skipFieldReinitialize = true;
    this.onChange();
  }

  private resolveEmittedOptionSource(): OptionSource | undefined {
    if (this.optionsMode === 'dynamic') {
      return this.buildDynamicOptionSource();
    }

    return undefined;
  }

  private buildDynamicOptionSource(): OptionSource | undefined {
    if (!this.selectedModuleSlug || !this.selectedDisplayColumn) {
      return undefined;
    }

    return {
      type: 'dynamic',
      endpoint: this.selectedModuleSlug,
      response: {
        labelKey: this.selectedDisplayColumn,
        valueKey: 'id',
        dataPath: 'data',
      },
    };
  }

    private readDynamicConfig(
      field: FormField
    ): { moduleSlug: string; displayColumn: string } | null {
      if (field.optionSource?.type !== 'dynamic' || !field.optionSource.endpoint) {
        return null;
      }

      return {
        moduleSlug: field.optionSource.endpoint,
        displayColumn: field.optionSource.response?.labelKey ?? 'name',
      };
    }

    readonly isModuleDropdownOpen = signal(false);

  toggleModuleDropdown(): void {
    this.isModuleDropdownOpen.update(value => !value);
  }

  closeModuleDropdown(): void {
    this.isModuleDropdownOpen.set(false);
  }

  selectModule(slug: string): void {
    if (!this.isFieldEditable || this.isModuleSlugDisabled(slug)) {
      return;
    }

    this.selectedModuleSlug = slug;
    this.onModuleChange(slug);
    this.closeModuleDropdown();
  }

  getSelectedModuleLabel(): string {
    const selected = this.availableModules.find(
      module => this.getModuleSlug(module) === this.selectedModuleSlug
    );

    return selected
      ? this.getModuleLabel(selected)
      : 'Select a module';
  }

  readonly isDisplayColumnDropdownOpen = signal(false);

  toggleDisplayColumnDropdown(): void {
    this.isDisplayColumnDropdownOpen.update(value => !value);
  }

  closeDisplayColumnDropdown(): void {
    this.isDisplayColumnDropdownOpen.set(false);
  }

  selectDisplayColumn(column: string): void {
    if (!this.isFieldEditable) {
      return;
    }

    this.selectedDisplayColumn = column;
    this.onDisplayColumnChange(column);
    this.closeDisplayColumnDropdown();
  }

  getSelectedDisplayColumnLabel(): string {
    return this.selectedDisplayColumn || 'Select a column';
  }

}
