import { MasterInvoice } from '../../interfaces/master-billing';
import { displayMoney } from '../../shared/utils/money.util';

export function formatInvoiceDate(value?: string | null): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatInvoiceStatus(status?: string | null): string {
  const raw = (status || '—').toString().trim().replace(/[_-]+/g, ' ');
  if (!raw || raw === '—') return '—';
  return raw
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(' ');
}

export function invoiceFileName(invoice: MasterInvoice): string {
  const number = (invoice.invoiceNumber || `invoice-${invoice.id}`).replace(/[^\w.-]+/g, '-');
  return `${number}.pdf`;
}

export function saveBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadGeneratedInvoice(invoice: MasterInvoice): void {
  saveBlob(buildSystemInvoicePdf(invoice), invoiceFileName(invoice));
}

export function saveRemoteOrGeneratedInvoice(blob: Blob, invoice: MasterInvoice): void {
  blob
    .slice(0, 8)
    .arrayBuffer()
    .then((buf) => {
      const sig = new TextDecoder().decode(buf);
      if (blob.size > 80 && sig.startsWith('%PDF')) {
        saveBlob(blob, invoiceFileName(invoice));
        return;
      }
      downloadGeneratedInvoice(invoice);
    })
    .catch(() => downloadGeneratedInvoice(invoice));
}

export function buildSystemInvoicePdf(invoice: MasterInvoice): Blob {
  const number = invoice.invoiceNumber || `INV-${invoice.id}`;
  const org = invoice.tenant?.name || '—';
  const domain = invoice.tenant?.subdomain || '';
  const status = formatInvoiceStatus(invoice.status);
  const amount = displayMoney(invoice.formattedAmount, invoice.amount);
  const invoiceDate = formatInvoiceDate(invoice.invoiceDate);
  const dueDate = formatInvoiceDate(invoice.dueDate);
  const paidAt = formatInvoiceDate(invoice.paidAt);
  const createdAt = formatInvoiceDate(invoice.createdAt);
  const currency = (invoice.currency || 'USD').toUpperCase();
  const description = `Platform subscription (${currency})`;

  const orange: Rgb = [0.918, 0.345, 0.047];
  const muted: Rgb = [0.58, 0.64, 0.72];
  const dark: Rgb = [0.06, 0.09, 0.16];
  const line: Rgb = [0.89, 0.91, 0.94];
  const left = 50;
  const right = 562;

  const ops: string[] = [
    strokeLine(left, 710, right, 710, orange, 2),
    strokeLine(left, 548, right, 548, line, 0.8),
    strokeLine(left, 516, right, 516, line, 0.8),
    'BT',
    pdfText('F2', 10, left, 752, 'EUSOCIAL', orange),
    pdfText('F2', 24, left, 722, 'Invoice', dark),
    pdfTextRight('F2', 14, right, 746, number, dark),
    pdfTextRight('F1', 11, right, 728, `Status: ${status}`, muted),
    pdfText('F2', 8, left, 688, 'BILL TO', muted),
    pdfText('F1', 12, left, 670, org, dark),
    ...(domain ? [pdfText('F1', 10, left, 654, domain, muted)] : []),
    pdfText('F2', 8, 330, 688, 'INVOICE DATE', muted),
    pdfText('F1', 12, 330, 670, invoiceDate, dark),
    pdfText('F2', 8, 330, 640, 'DUE DATE', muted),
    pdfText('F1', 12, 330, 622, dueDate, dark),
    pdfText('F2', 8, 330, 592, 'PAID AT', muted),
    pdfText('F1', 12, 330, 574, paidAt, dark),
    pdfText('F2', 8, left, 556, 'DESCRIPTION', muted),
    pdfTextRight('F2', 8, right, 556, 'AMOUNT', muted),
    pdfText('F1', 12, left, 528, description, dark),
    pdfTextRight('F1', 12, right, 528, amount, dark),
    pdfTextRight('F2', 13, right - 130, 492, 'Total', dark),
    pdfTextRight('F2', 13, right, 492, amount, dark),
    pdfText(
      'F1',
      9,
      left,
      80,
      `Generated by Eusocial on ${createdAt}. This is a system invoice, not a Stripe receipt.`,
      muted
    ),
    'ET',
  ];

  return assemblePdf(ops.join('\n') + '\n');
}

type Rgb = [number, number, number];

function pdfText(
  font: 'F1' | 'F2',
  size: number,
  x: number,
  y: number,
  value: string,
  rgb: Rgb
): string {
  return [
    `${rgb[0]} ${rgb[1]} ${rgb[2]} rg`,
    `/${font} ${size} Tf`,
    `1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm`,
    `${pdfLiteral(value)} Tj`,
  ].join('\n');
}

function pdfTextRight(
  font: 'F1' | 'F2',
  size: number,
  xRight: number,
  y: number,
  value: string,
  rgb: Rgb
): string {
  const width = value.length * size * 0.5;
  return pdfText(font, size, xRight - width, y, value, rgb);
}

function strokeLine(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  rgb: Rgb,
  width: number
): string {
  return [
    `${rgb[0]} ${rgb[1]} ${rgb[2]} RG`,
    `${width} w`,
    `${x1} ${y1} m`,
    `${x2} ${y2} l`,
    'S',
  ].join('\n');
}

function pdfLiteral(text: string): string {
  let out = '';
  for (const ch of Array.from(text || '')) {
    const code = ch.codePointAt(0) ?? 32;
    if (ch === '\\' || ch === '(' || ch === ')') {
      out += `\\${ch}`;
    } else if (code === 9 || code === 10 || code === 13) {
      out += ' ';
    } else if (code >= 32 && code <= 126) {
      out += ch;
    } else if (code <= 255) {
      out += `\\${code.toString(8).padStart(3, '0')}`;
    } else {
      const folded = ch.normalize('NFKD').replace(/[\u0300-\u036f]/g, '');
      out += folded && folded.charCodeAt(0) < 128 ? folded : '?';
    }
  }
  return `(${out})`;
}

function assemblePdf(contentStream: string): Blob {
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${contentStream.length} >>\nstream\n${contentStream}endstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
  ];

  let file = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(file.length);
    file += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xref = file.length;
  file += `xref\n0 ${objects.length + 1}\n`;
  file += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    file += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  file += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return new Blob([file], { type: 'application/pdf' });
}
