import { Component, HostListener, OnDestroy, OnInit } from '@angular/core';
import { NavigationEnd, Router } from '@angular/router';
import { Subject, filter, takeUntil } from 'rxjs';
import { Auth } from '../../services/auth';
import { User } from '../../interfaces/user';

interface PageMeta {
  title: string;
  subtitle: string;
}

@Component({
  selector: 'app-navbar',
  standalone: false,
  templateUrl: './navbar.html',
  styleUrl: './navbar.scss',
})
export class Navbar implements OnInit, OnDestroy {
  user: User | null = null;
  dropdownOpen = false;
  page: PageMeta = {
    title: 'Super Admin Dashboard',
    subtitle: 'Overview of your multi-organization SaaS platform.',
  };

  private readonly destroy$ = new Subject<void>();

  private readonly pageMap: Record<string, PageMeta> = {
    '/dashboard': {
      title: 'Super Admin Dashboard',
      subtitle: 'Overview of your multi-organization SaaS platform.',
    },
    '/tenants': {
      title: 'Organizations',
      subtitle: 'Manage all organizations on the platform.',
    },
    '/tenants/create': {
      title: 'Create Organization',
      subtitle: 'Set up a new organization, plan, and admin user.',
    },
    '/users': {
      title: 'Users',
      subtitle: 'Manage super admin users and access.',
    },
    '/roles': {
      title: 'Roles & Permissions',
      subtitle: 'Configure platform roles and permissions.',
    },
    '/profile': {
      title: 'My Profile',
      subtitle: 'Update your account details and password.',
    },
    '/permissions': {
      title: 'Permissions',
      subtitle: 'Manage fine-grained access controls.',
    },
    '/products': {
      title: 'Products',
      subtitle: 'Manage product catalog entries.',
    },
    '/subscriptions': {
      title: 'Subscriptions',
      subtitle: 'Monitor and manage organization subscriptions.',
    },
    '/plans': {
      title: 'Plan Management',
      subtitle: 'Create and manage subscription plans.',
    },
    '/invoices': {
      title: 'Billing & Invoices',
      subtitle: 'Track invoices, payments, and platform revenue.',
    },
  };

  private readonly editOrganizationPage: PageMeta = {
    title: 'Edit Organization',
    subtitle: 'Update organization details and contact information.',
  };

  private readonly viewOrganizationPage: PageMeta = {
    title: 'View Organization',
    subtitle: 'Organization details and subscription information.',
  };

  private readonly viewSubscriptionPage: PageMeta = {
    title: 'View Subscription',
    subtitle: 'Subscription details for this organization.',
  };

  private readonly viewInvoicePage: PageMeta = {
    title: 'View Invoice',
    subtitle: 'Invoice generated by the platform.',
  };

  private readonly viewPlanPage: PageMeta = {
    title: 'View Plan',
    subtitle: 'Plan details, features, and accessibility.',
  };

  private readonly editPlanPage: PageMeta = {
    title: 'Edit Plan',
    subtitle: 'Update plan pricing, features, and accessibility.',
  };

  private readonly createPlanPage: PageMeta = {
    title: 'Create Plan',
    subtitle: 'Set up a new subscription plan.',
  };

  constructor(private auth: Auth, private router: Router) {}

  ngOnInit(): void {
    this.auth.currentUser$.pipe(takeUntil(this.destroy$)).subscribe((user) => {
      this.user = user;
    });

    this.updatePage(this.router.url);
    this.router.events
      .pipe(
        filter((e): e is NavigationEnd => e instanceof NavigationEnd),
        takeUntil(this.destroy$)
      )
      .subscribe((e) => this.updatePage(e.urlAfterRedirects));
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  get displayName(): string {
    return this.user?.name || 'Super Admin';
  }

  get displayEmail(): string {
    return this.user?.email || '';
  }

  initials(name: string): string {
    const parts = name.trim().split(/\s+/).filter(Boolean);
    if (!parts.length) return 'SA';
    if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
    return `${parts[0][0]}${parts[1][0]}`.toUpperCase();
  }

  logout(): void {
    this.closeDropdown();
    this.auth.logout();
  }

  toggleDropdown(): void {
    this.dropdownOpen = !this.dropdownOpen;
  }

  closeDropdown(): void {
    this.dropdownOpen = false;
  }

  @HostListener('document:click', ['$event'])
  handleClickOutside(event: Event): void {
    const target = event.target as HTMLElement;
    if (!target.closest('.profile-dropdown')) {
      this.closeDropdown();
    }
  }

  private updatePage(url: string): void {
    const path = url.split('?')[0];

    if (/^\/tenants\/\d+\/view$/.test(path)) {
      this.page = this.viewOrganizationPage;
      return;
    }

    if (/^\/tenants\/\d+\/edit$/.test(path)) {
      this.page = this.editOrganizationPage;
      return;
    }

    if (/^\/subscriptions\/\d+\/view$/.test(path)) {
      this.page = this.viewSubscriptionPage;
      return;
    }

    if (/^\/invoices\/\d+\/view$/.test(path)) {
      this.page = this.viewInvoicePage;
      return;
    }

    if (/^\/plans\/create$/.test(path)) {
      this.page = this.createPlanPage;
      return;
    }

    if (/^\/plans\/\d+\/view$/.test(path)) {
      this.page = this.viewPlanPage;
      return;
    }

    if (/^\/plans\/\d+\/edit$/.test(path)) {
      this.page = this.editPlanPage;
      return;
    }

    const match = Object.keys(this.pageMap)
      .sort((a, b) => b.length - a.length)
      .find((key) => path === key || path.startsWith(`${key}/`));

    this.page = match
      ? this.pageMap[match]
      : {
          title: 'Super Admin',
          subtitle: 'Platform administration console.',
        };
  }
}
